name: Compile LaTeX PDF

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up TeX Live (full installation)
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full  # Install the full TeX Live distribution

    - name: Compile LaTeX document
      run: |
        pdflatex -interaction=nonstopmode main.tex || exit 1  # Compile LaTeX
        pdflatex -interaction=nonstopmode main.tex || exit 1  # Compile twice for proper references

    - name: Create Release and Upload PDF
      uses: softprops/action-gh-release@v1  # Automatically create a GitHub release
      with:
        files: main.pdf  # Attach the compiled PDF to the release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token to authenticate with the GitHub API
